createTodo:
  handler: src/handlers/create.default
  apim:
    api: ${self:service}-api
    backend: ${self:service}-backend
    operations:
      - method: POST
        urlTemplate: /
        displayName: create-todo
  events:
    - http: true
      name: req
      methods:
        - POST
      authLevel: function
      route: todo
listTodos:
  handler: src/handlers/list.default
  apim:
    api: ${self:service}-api
    backend: ${self:service}-backend
    operations:
      - method: get
        urlTemplate: /
        displayName: list-todos
  events:
    - http: true
      name: req
      methods:
        - GET
      authLevel: function
      route: todo
getTodo:
  handler: src/handlers/get.default
  apim:
    api: ${self:service}-api
    backend: ${self:service}-backend
    operations:
      - method: get
        urlTemplate: /{todo_id}
        templateParameters:
          - name: todo_id
            required: true
            type: int
        displayName: get-todo
  events:
    - http: true
      name: req
      methods:
        - GET
      authLevel: function
      route: todo/{todo_id}
updateTodo:
  handler: src/handlers/update.default
  apim:
    api: ${self:service}-api
    backend: ${self:service}-backend
    operations:
      - method: put
        urlTemplate: /{todo_id}
        templateParameters:
          - name: todo_id
            required: true
            type: int
        displayName: update-todo
  events:
    - http: true
      name: req
      methods:
        - PUT
      authLevel: function
      route: tood/{todo_id}
rmTodo:
  handler: src/handlers/rm.default
  apim:
    api: ${self:service}-api
    backend: ${self:service}-backend
    operations:
      - method: DELETE
        urlTemplate: /{todo_id}
        templateParameters:
          - name: todo_id
            required: true
            type: int
        displayName: remove-todo
  events:
    - http: true
      name: req
      methods:
        - DELETE
      authLevel: function
      route: todo/{todo_id}