name: ${file(../base/config/apim.yml):name}
apis: 
  - name: ${file(../base.yml):services.task}-api
    subscriptionRequired: false
    displayName: ${file(../base.yml):services.task}-api
    description: Task API
    protocols:
      - https
    path: ${file(../base.yml):services.task}
    authorization: none
backends:
  - name: ${self:service}-backend
    url: ${self:service}
cors: ${file(../base.yml):cors}
jwtValidate: ${file(../base.yml):jwtValidate}